name: GrimList
main: com.caelusrp.grimlist.grimlist
website: http://caelusrp.com
version: 2.0
author: Nicholas Badger (A.K.A. FerusGrim)
description: Plugin created to be the whitelist for Caelus Roleplay servers.
commands:
  whitelist:
    description: GrimList commands.
    usage: /<command> <variable> [input]
permissions:
    whitelist.*:
        description: Grants all GrimList permissions.
        children:
            grimlist.add: true
            grimlist.remove: true
            grimlist.print-failure: true
            grimlist.reload: true
            grimlist.refresh: true
            grimlist.toggle: true
    grimlist.add:
        description: Add users to the whitelist.
        default: op
    grimlist.remove:
        description: Remove users from the whitelist.
        default: op
    grimlist.print-failure:
        description: View when a player is disconnected.
        default: op
    grimlist.reload:
        description: Reload GrimList configuration.
        default: op
    grimlist.refresh:
        description: Refreshes the whitelist.
        default: op
    grimlist.toggle:
        description: Toggle the whitelist off/on.
        default: op