name: GrimList
main: com.caelusrp.grimlist.grimlist
website: http://caelusrp.com
version: 2.0
author: Nicholas Badger (A.K.A. FerusGrim)
description: Plugin created to be the whitelist for Caelus Roleplay servers.
commands:
  whitelist:
    description: GrimList commands.
    usage: /<command> <variable> [input]
permissions:
    whitelist.*:
        description: Grants all GrimList permissions.
        children:
            whitelist.add: true
            whitelist.remove: true
            whitelist.print-failure: true
            whitelist.reload: true
            whitelist.refresh: true
            whitelist.toggle: true
    whitelist.add:
        description: Add users to the whitelist.
        default: op
    whitelist.remove:
        description: Remove users from the whitelist.
        default: op
    whitelist.print-failure:
        description: View when a player is disconnected.
        default: op
    whitelist.reload:
        description: Reload GrimList configuration.
        default: op
    whitelist.refresh:
        description: Refreshes the whitelist.
        default: op
    whitelist.toggle:
        description: Toggle the whitelist off/on.
        default: op