# Configurations can be confusing, so I tried to keep as much as I could
# as simple 'true/false' booleans. If you get confused about any configuration
# options below, check out the BukkitDev page for the configuration help section:
# http://dev.bukkit.org/bukkit-plugins/grimlist/pages/configuration/

Whitelist: true
Metrics: true
Updater: true
DebugMessages: false
SaveQueries: true
KickRemove: true
AlwaysLookup: false
Focus: file
LogUsage:
  Add: false
  Remove: false
  Delete: false
  View: false
Notify:
  Console: false
  Player: true
MySQL:
  host: localhost
  port: 3306
  database: 'grimlist
  username: root
  password: toor
Url:
  link: http://localhost/playerdata.yml
  update-interval: 120