name: GrimList
version: 3.0.3
main: io.github.ferusgrim.GrimList.GrimList
description: Advanced whitelisting plugin for Bukkit Servers.
author: FerusGrim
website: http://ferusgrim.github.io/
commands:
  whitelist:
    description: Main command for this plugin.
    aliases: [grimlist, wl, gl]
    usage: |
      /&lt;whitelist&gt; [arguments] [player/msg]
      Example: /&lt;whitelist&gt; add/remove Notch - Adds or Removes Notch from the whitelist.
      Example: /&lt;whitelist&gt; set focus mysql - Changes focus to MySQL.
permissions:
  grimlist.*:
    description: Grants access to all commands.
    children:
      grimlist.add: true
      grimlist.remove: true
      grimlist.delete: true
      grimlist.view: true
      grimlist.getid: true
      grimlist.update: true
      grimlist.help: true
      grimlist.set: true
  grimlist.add:
    description: Allows you to add a player to the whitelist.
    default: op
  grimlist.remove:
    description: Allows you to remove a player from the whitelist.
    default: op
  grimlist.delete:
    description: Deletes a playerdata entry.
    default: op
  grimlist.view:
    description: Allows you to view player information in-game.
    default: op
  grimlist.getid:
    description: Allows player to get the UUID of another player.
    default: op
  grimlist.set:
    description: Allows you to edit configuration while in-game.
    default: op
  grimlist.help:
    description: Allows you to view the help/usage message.
    default: op
  grimlist.update:
    description: Notifies player on login if an update is available.
    default: op
  grimlist.notify:
    description: Notifies player of failed login attempts.
    default: op